### ISSUE TITLE
Space bar as Control

### ISSUE THREAD

**Issue by bard** [kui/rbindkeys#1]
Thanks for sharing rbindkeys!

I'm wondering, can it be used to make the space bar as Control when pressed with another key (like [space2ctrl](https://github.com/r0adrunner/Space2Ctrl))?

**Comment by kui** [comment]
Yes.

To use the space bar as Control, write `~/.rbindkeys` as below:

~~~~~~~~~~~~~~~~~~~~ruby
pre_bind_key KEY_SPACE, KEY_LEFTCTRL
~~~~~~~~~~~~~~~~~~~~

See [my config](https://github.com/kui/dotfiles/blob/master/dotfiles/rbindkeys.rb), if you prefer.
